### ISSUE TITLE
DLL not found

### ISSUE THREAD

**Issue by remi-pr** [smestern/pyCEDFS#5]
Hi,

Thanks for sharing this potentially very useful library. Unfortunately, after installing it to give it a try (trying to simplify the toolchain from stfio) I ran into a DLL issue that stopped me when I tried to import the package. Apparently the ctype.CDLL call fails because it can't find the DLL (FileNotFoundError). This is surprising because the CFS64.dll is there, and the path is correct. I tried all the suggestions I could find on Google (be in the directory before loading it, adding the directory to the path, etc.) but not luck. Do you have any other suggestion / idea? Encountered this issue before?
Thanks.

**Comment by smestern** [comment]
Hello,

Apologies for the slow response! I have encountered this before, the ctypes library gets a bit finicky about where the DLL is packaged. I will look into this asap! Two quick questions:

- Did you install via PIP?
- What operating system are you using?

**Comment by remi-pr** [comment]
Hi,

No worries for the response, it is summer for everyone (and apparently this response never got sent, so I am even more guilty of it).

ctypes is indeed .. finicky, this is an understatement.

I tried under Windows, and I used pip indeed. Would another install route be easier? Would this even work under another OS than Windows?

Cheers and thanks for looking into it.

**Comment by smestern** [comment]
PIP and Windows are definitely the best options! I will keep trying to replicate the issue. Currently I have tested on python 3.7 on 64 bit windows, without much issue. It looks like in 3.8 the dll search mechanism has changed, will be looking into this asap!

**Comment by remi-pr** [comment]
Just to let you know that I tried on a different computer, using Python 3.7, and I got it to work. I will need to investigate some more. Let me know if you find something

**Comment by remi-pr** [comment]
But still impossible to get it to work on the lab computer... I am wondering if there is an hidden dependency, another DLL used by the CFS64.dll. That could trigger this error I think

**Comment by smestern** [comment]
I was unable to replicate the issue. However I tried pushing an update that may solve the issue for >3.8 issues entirely. I will dig further into the DLL! It does rely on a lot of legacy code that may be missing on the given computer.

**Comment by a-hurst** [comment]
@remi-pr @smestern I think I've solved this with #6. Rémi was right: CFS64.dll has a hidden dependency on MSCVR100.dll, which is part of the Visual Studio C++ 2010 Runtime. Once you install that, pyCEDFS should work as intended!

**Comment by smestern** [comment]
Thank you @a-hurst for the fix! I have pushed the changes accordingly to PyPi. Seems to be working flawlessly!

**Comment by remi-pr** [comment]
Great news. Thanks @a-hurst for the find! Thanks @smestern for the update. I will give this new version a try soon.
